# Generated by Django 3.2 on 2023-02-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_rename_product_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prject_name',
            new_name='project_name',
        ),
    ]
