# Generated by Django 3.2 on 2023-02-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20230204_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectshow',
            name='ProjectTime',
            field=models.CharField(default=23, max_length=10),
            preserve_default=False,
        ),
    ]
