# Generated by Django 3.2 on 2023-06-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_projectshow_desc2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectshow',
            name='Feature1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='Feature2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='Feature3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='Feature4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='Feature5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='desc2',
            field=models.TextField(blank=True),
        ),
    ]
