# Generated by Django 3.2 on 2023-02-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='Project/images')),
                ('Certificate_name', models.CharField(max_length=100)),
                ('Certificate_tag', models.CharField(max_length=50)),
                ('Certificate_date', models.CharField(max_length=20)),
            ],
        ),
    ]
